export default {
    listItem: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderBottom: 'solid',
        borderWidth: '1px',
        borderColor: 'rgba(255,255,255,0.2)',
        padding: '4px',
        glexGrow: 1,
    },
    list: {
        padding: 0,
        margin: 0,
        listStyleType: 'none',
        flex: 1,
    },
    fileButton: {
        default: {
            backgroundColor: 'rgba(34, 44, 82,100)',
            border: 'solid',
            borderWidth: '0px',
            color: 'rgba(255,255,255,0.87)',
            marginRight: '4px',
            padding: '8px',
            borderRadius: '5px',
        },
        hover: {
            backgroundColor: 'rgba(255,255,255,0.15)',
            border: 'solid',
            borderWidth: '0px',
            color: 'rgba(255,255,255,0.87)',
            marginRight: '4px',
            padding: '8px',
            borderRadius: '5px',
        },
        press: {
            backgroundColor: 'rgba(255,255,255,0.25)',
            border: 'solid',
            borderWidth: '0px',
            color: 'rgba(255,255,255,0.87)',
            marginRight: '4px',
            padding: '8px',
            borderRadius: '5px',
        },
    },
    listButton: {
        default: {
            backgroundColor: 'rgba(0,0,0,0)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: '30px',
            minHeight: '30px',
            borderWidth: '0px',
            borderColor: 'rgba(255,255,255,0.7)',
            borderRadius: '50%',
            color: 'rgba(255,255,255,0.87)',
            padding: '0px',
        },
        hover: {
            backgroundColor: 'rgba(190,0,0,1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: '30px',
            minHeight: '30px',
            borderWidth: '0px',
            borderColor: 'rgba(255,255,255,0.7)',
            borderRadius: '50%',
            color: 'rgba(255,255,255,0.87)',
            padding: '0px',
        },
        press: {
            backgroundColor: 'rgba(199,93,100,1)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            minWidth: '30px',
            minHeight: '30px',
            borderWidth: '0px',
            borderColor: 'rgba(255,255,255,0.7)',
            borderRadius: '50%',
            color: 'rgba(255,255,255,0.87)',
            padding: '0px',
        },
    },
    header: {
        display: 'flex',
        color: 'rgba(255,255,255,0.87)',
        alignItems: 'center',
        paddingRight: '10px',
        paddingLeft: '4px',
        fontSize: '20px',
        fontWeight: 'bold',
    },
};
