export default {
    processingContainer: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        backgroundColor: '#121212',
        overflow: 'auto',
    },
    fileInputsContainer: {
        display: 'flex',
        flexDirection: 'row',
    },
    fileButtonsContainer: {
        display: 'flex',
        flexDirection: 'row',
    },
    fileListContainer: {
        display: 'flex',
        flexGrow: 1,
        marginRight: '4px',
        marginLeft: '4px',
        marginBottom: '4px',
        backgroundColor: '#1a202d',
        border: 'solid',
        borderColor: 'rgba(255,255,255,0.7)',
        borderWidth: '1px',
        minHeight: '100px',
    },
    editableListContainer: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
    },
    headerContainer: {
        display: 'flex',
        flexDirection: 'row',
        padding: '4px',
    },
    settingsContainer: {
        display: 'flex',
        flexDirection: 'column',
        margin: '4px',
    },
    booleanSettingsContainer: {
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        margin: '4px',
    },
    textSettingsContainer: {
        display: 'flex',
        flexDirection: 'column',
        margin: '4px',
    },
    logContainer: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        margin: '4px',
    },
    textSettingContainer: {
        display: 'flex',
        flexDirection: 'column',
        paddingLeft: '8px',
        paddingRight: '8px',
        paddingTop: '4px',
        paddingBottom: '4px',
    },
    checkboxSettingContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        width: '175px',
        paddingLeft: '8px',
        paddingRight: '8px',
        paddingTop: '4px',
        paddingBottom: '4px',
        margin: '2px',
        border: 'solid',
        borderWidth: '1px',
        borderColor: 'rgba(255,255,255,0.7)',
    },
    instructionsContainer: {
        display: 'flex',
        width: '100%',
        justifyContent: 'center',
        alignItems: 'center',
    }
};
