export default {
    rootContainer: {
        display: 'flex',
        flexDirection: 'column',
        flex: 1,
        height: '100%',
        color: 'rgba(255,255,255,0.87)',
    },
    loadingContainer: {
        display: 'flex',
        flexDirection: 'column',
        justifyContent: 'center',
        alignItems: 'center',
        height: '100%',
        backgroundColor: '#121212',
        color: 'rgba(255,255,255,0.87)',
        fontSize: '20px',
    },
    menuContainer: {
        display: 'flex',
        flexDirection: 'row',
        justifyContent: 'space-between',
        backgroundColor: '#313c56',
        WebkitAppRegion: 'drag',
    },
    buttonContainer: {
        display: 'flex',
        flexDirection: 'row',
        WebkitAppRegion: 'no-drag',
    },
    menuButton: {
        default: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(0,0,0,0)',
        },
        hover: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.15)',
        },
        press: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.25)',
        },
    },
    closeButton: {
        default: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(0,0,0,0)',
        },
        hover: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(190,0,0,1)',
        },
        press: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            width: '45px',
            lineHeight: '0px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(199,93,100,1)',
        },
    },
    link: {
        default: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.55)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(0,0,0,0)',
        },
        hover: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.55)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.15)',
        },
        press: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.55)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.25)',
        },
    },
    activeLink: {
        default: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
        },
        hover: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.15)',
        },
        press: {
            textDecoration: 'none',
            color: 'rgba(255,255,255,0.87)',
            paddingTop: '8px',
            paddingBottom: '8px',
            paddingLeft: '8px',
            paddingRight: '8px',
            fontSize: '14px',
            border: 'none',
            backgroundColor: 'rgba(200,200,200,0.25)',
        },
    },
};
